openapi: "3.0.2"
info:
  title: "Zoomos API"
  description: “Описание запросов и параметров запросов API Zoomos”
  version: "1.0.0"
  contact:
    name: support
    email: support@zoomos.by
servers:
  - url: https://api.zoomos.by/

tags:
  # - name: app-project
  #   description: Amet vix donec sapientem atomorum sagittis epicurei offendit mediocritatem legimus. Mollis error eloquentiam doctus nonumes. Perpetua ne veri laudem venenatis integer senserit ignota.
  # - name: item
  #   description: Placerat mea vocibus eripuit fuisset necessitatibus eius ante epicuri deseruisse. Theophrastus sit no eloquentiam ne varius. Detraxit assueverit contentiones luctus aliquip.
  - name: Прайс лист
    description: <div><p><code>API</code> ZOOMOS доступно только авторизованным пользователям. Идентификация происходит с помощью авторизационных ключей, выдаваемых системой ZOOMOS.</p>


paths:
  /pricelist?key={api-key}:
    $ref: './endpoints/pricelist.yaml#/endpoint'

  # /app-projectsdsdfsfs:
  #   $ref: './endpoints/app-projects.yaml#/endpoint'
  # /app-projects/{app_project_id}:
  #   $ref: './endpoints/app-project.yaml#/endpoint'
  # /app-projects/{app_project_id}/archive:
  #   $ref: './endpoints/app-project-archive.yaml#/endpoint'

  # /app-projects/{app_project_id}/items/{item_id}:
  #   $ref: './endpoints/item.yaml#/endpoint'
  # /app-projects/{app_project_id}/items:
  #   $ref: './endpoints/items.yaml#/endpoint'